export const GET_INQUIRY = "GET_INQUIRY";
export const SET_CURRENT_INQUIRY = "SET_CURRENT_INQUIRY";

export const GET_INQUIRY_SUCCESS = "GET_INQUIRY_SUCCESS";
export const GET_INQUIRIES = "GET_INQUIRIES";
export const GET_INQUIRIES_SUCCESS = "GET_INQUIRIES_SUCCESS";

export const ACCEPT_INQUIRY = "ACCEPT_INQUIRY";
export const ACCEPT_INQUIRY_SUCCESS = "ACCEPT_INQUIRY_SUCCESS";
export const CANCEL_INQUIRY = "CANCEL_INQUIRY";
export const CANCEL_INQUIRY_SUCCESS = "CANCEL_INQUIRY_SUCCESS";
