export const GET_BOOKING = "GET_BOOKING";
export const SET_CURRENT_BOOKING = "SET_CURRENT_BOOKING";

export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKINGS = "GET_BOOKINGS";
export const GET_BOOKINGS_SUCCESS = "GET_BOOKINGS_SUCCESS";

export const ACCEPT_BOOKING = "ACCEPT_BOOKING";
export const ACCEPT_BOOKING_SUCCESS = "ACCEPT_BOOKING_SUCCESS";
export const CANCEL_BOOKING = "CANCEL_BOOKING";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";
